# Numpy

    * numerical pyhton or numeric python
    * numpy is a programming language that deals with multi dimensional arrays  and matrices
    * numpy supports a large no of mathematical operations
    

# why use numpy

    * numpy is memory efficieny meaning it can handle the vast amount of data more acessible than any oher library
    * especially for matrix multiplication and reshaping
    * on top of that numpy is fast in fact

# how to install numpy

    * numpy is installed default in anaconda

In [1]:
import numpy as np


In [2]:
print(np.__version__)

1.19.2


In [3]:
print(np.array([2,4,6,8,]))

[2 4 6 8]


In [4]:
np.array([2,4,6,8,])

array([2, 4, 6, 8])

In [18]:
data=np.array([1,2,3,4])
data1=np.array([5,9,8,7])
print(data+data1)
print(data-data1)

[ 6 11 11 11]
[-4 -7 -5 -3]


In [10]:
a=np.array([[1,2,3,4],[5,6,9,7],[11,55,8,963]])
print(a)

[[  1   2   3   4]
 [  5   6   9   7]
 [ 11  55   8 963]]


In [13]:
d=np.array([[1,2,3,4],[5,6,9,7]])
print(np.shape(d))
print(d.dtype)

(2, 4)
int32


In [16]:
d1=np.array([[1.1,2.2,3.3,4.4],[5.4,6.5,9.9,7.7]])
print(np.shape(d1))
print(d1.dtype)

(2, 4)
float64


In [5]:
import numpy as np

In [7]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [9]:
data=np.array([[1,2,3,4],[5,6,7,8]])
print(data)
print(data.mean())
print(np.median(data))
print(np.mod(2,3))

[[1 2 3 4]
 [5 6 7 8]]
4.5
4.5
2


In [10]:
np.random.normal(5,4,10)

array([ 8.73022249,  9.04727955,  9.13191995,  0.79822369, -1.69455038,
        2.00664252,  6.48688675,  9.8588361 , 12.0496587 ,  6.12928477])

In [11]:
d=np.random.randint(1,65,(3,3))
d

array([[26, 28, 32],
       [25, 39, 12],
       [41, 28, 17]])

In [12]:
d.min()

12

In [13]:
d.max()

41

In [14]:
d.mean()

27.555555555555557

In [15]:
d.std()

8.782699042386445

In [16]:
d.T

array([[26, 25, 41],
       [28, 39, 28],
       [32, 12, 17]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
data.dot(data1)

75

In [21]:
data1

array([5, 9, 8, 7])

In [20]:
np.array([data1,pow(data1,3)])

array([[  5,   9,   8,   7],
       [125, 729, 512, 343]])

In [30]:
np.linspace(18,50,num=9)

array([18., 22., 26., 30., 34., 38., 42., 46., 50.])